name: norns-test-artfwo
version: '0.1'
summary: changes. travels. is open to possibilities.
description: |
  norns is many sound instruments. it connects to grids, MIDI and
  other objects. norns lets you define its behavior with scripts and
  DSP.

  past. present. future. norns is many tomorrows.

grade: devel
confinement: devmode

parts:
  nanomsg:
    source: https://github.com/nanomsg/nanomsg.git
    source-depth: 1
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr

  libmonome:
    source: https://github.com/monome/libmonome.git
    source-depth: 1
    plugin: waf
    configflags:
      - --prefix=/usr
    build-packages:
      - libudev-dev
      - liblo-dev
    stage-packages:
      - liblo7

  jack2:
    source: https://github.com/jackaudio/jack2.git
    source-depth: 1
    plugin: waf
    configflags:
      - --prefix=/usr
    build-packages:
      - libasound2-dev
      - libsamplerate0-dev
    stage-packages:
      - libasound2
      - libsamplerate0
      - libsndfile1

  supercollider:
    after: [jack2]
    source: https://github.com/supercollider/supercollider.git
    source-depth: 1
    disable-parallel: true
    override-pull: |
      snapcraftctl pull
      echo "applying pinned_cpu_sclang_terminal.diff..."
      git apply --verbose ../../../patches/pinned_cpu_sclang_terminal.diff
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DNATIVE=1
      - -DSSE=0
      - -DSSE2=0
      - -DENABLE_TESTSUITE=0
      - -DCMAKE_SKIP_RPATH=1
      - -DLIBSCSYNTH=0
      - -DSUPERNOVA=0
      - -DSC_WII=0
      - -DSC_IDE=0
      - -DSC_QT=0
      - -DSC_ED=0
      - -DSC_EL=0
      - -DSC_VIM=0
    build-packages:
      - libasound2-dev
      - libavahi-client-dev
      - libfftw3-dev
      - libicu-dev
      - libreadline-dev
      - libsndfile1-dev
      - libudev-dev
      - libxt-dev
    stage-packages:
      - libx11-6
      - libxau6
      - libxdmcp6
      - libavahi-client3
      - libfftw3-single3
      - libxcb1

  sc3-plugins:
    after: [supercollider]
    source: https://github.com/supercollider/sc3-plugins.git
    source-depth: 1
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DNATIVE=1
      - -DSUPERNOVA=0
      - -DNOVA_SIMD=0
      - -DSC_PATH=$SNAPCRAFT_STAGE/usr/include/SuperCollider

  norns:
    after: [nanomsg, libmonome, jack2, supercollider]
    source: git@github.com:catfact/norns.git
    source-depth: 1
    plugin: waf
    configflags:
      - --prefix=/usr
      - CXXFLAGS=-I$SNAPCRAFT_STAGE/usr/include/SuperCollider/plugin_interface
      - CXXFLAGS=-I$SNAPCRAFT_STAGE/usr/include/SuperCollider/common
    build-packages:
      - libasound2-dev
      - liblo-dev
      - libudev-dev
      - libevdev-dev
      - libcairo2-dev
      - liblua5.3-dev
      - libavahi-compat-libdnssd-dev
    stage-packages:
      - libxext6
      - libxrender1
      - libcairo2
      - libavahi-compat-libdnssd1
      - libevdev2
      - libfontconfig1
      - liblua5.3-0
      - libpixman-1-0
      - libxcb-render0
      - libxcb-shm0

apps:
  norns:
    command: usr/bin/matron
    plugs:
      - alsa
      - avahi-control
      - avahi-observe
      - framebuffer
      - gpio
      #- gpio-memory-control
      - hardware-observe
      - hidraw
      - home
      - i2c
      - mount-observe
      - network
      - network-bind
      #- network-control
      - network-manager
      - network-observe
      # might need this for jackd
      #- physical-memory-control
      #- physical-memory-observe
      - process-control
      - raw-usb
      - removable-media
      - serial-port
      - shutdown
      # is this required?
      - snapd-control
      - spi
      # is this required?
      - system-observe
      #- time-control
      #- time-control
      #- timezone-control
